package mlir

/*
#cgo CFLAGS: -fPIC -O0 -g

#cgo LDFLAGS: -g
#cgo LDFLAGS: -lstdc++ -lrt -ldl -lpthread -lm -lz -ltinfo -lzstd
#cgo LDFLAGS: -lMLIRAffineAnalysis
#cgo LDFLAGS: -lMLIRAffineDialect
#cgo LDFLAGS: -lMLIRAffineToStandard
#cgo LDFLAGS: -lMLIRAffineTransformOps
#cgo LDFLAGS: -lMLIRAffineTransforms
#cgo LDFLAGS: -lMLIRAffineUtils
#cgo LDFLAGS: -lMLIRAMDGPUDialect
#cgo LDFLAGS: -lMLIRAMDGPUToROCDL
#cgo LDFLAGS: -lMLIRAMDGPUTransforms
#cgo LDFLAGS: -lMLIRAMDGPUUtils
#cgo LDFLAGS: -lMLIRAMXDialect
#cgo LDFLAGS: -lMLIRAMXTransforms
#cgo LDFLAGS: -lMLIRAnalysis
#cgo LDFLAGS: -lMLIRArithAttrToLLVMConversion
#cgo LDFLAGS: -lMLIRArithDialect
#cgo LDFLAGS: -lMLIRArithToAMDGPU
#cgo LDFLAGS: -lMLIRArithToArmSME
#cgo LDFLAGS: -lMLIRArithToEmitC
#cgo LDFLAGS: -lMLIRArithToLLVM
#cgo LDFLAGS: -lMLIRArithToSPIRV
#cgo LDFLAGS: -lMLIRArithTransforms
#cgo LDFLAGS: -lMLIRArithUtils
#cgo LDFLAGS: -lMLIRArithValueBoundsOpInterfaceImpl
#cgo LDFLAGS: -lMLIRArmNeon2dToIntr
#cgo LDFLAGS: -lMLIRArmNeonDialect
#cgo LDFLAGS: -lMLIRArmNeonToLLVMIRTranslation
#cgo LDFLAGS: -lMLIRArmNeonTransforms
#cgo LDFLAGS: -lMLIRArmNeonVectorTransformOps
#cgo LDFLAGS: -lMLIRArmSMEDialect
#cgo LDFLAGS: -lMLIRArmSMEToLLVM
#cgo LDFLAGS: -lMLIRArmSMEToLLVMIRTranslation
#cgo LDFLAGS: -lMLIRArmSMEToSCF
#cgo LDFLAGS: -lMLIRArmSMETransforms
#cgo LDFLAGS: -lMLIRArmSVEDialect
#cgo LDFLAGS: -lMLIRArmSVEToLLVMIRTranslation
#cgo LDFLAGS: -lMLIRArmSVETransforms
#cgo LDFLAGS: -lMLIRArmSVEVectorTransformOps
#cgo LDFLAGS: -lMLIRAsmParser
#cgo LDFLAGS: -lMLIRAsyncDialect
#cgo LDFLAGS: -lMLIRAsyncToLLVM
#cgo LDFLAGS: -lMLIRAsyncTransforms
#cgo LDFLAGS: -lMLIRBufferizationDialect
#cgo LDFLAGS: -lMLIRBufferizationPipelines
#cgo LDFLAGS: -lMLIRBufferizationToMemRef
#cgo LDFLAGS: -lMLIRBufferizationTransformOps
#cgo LDFLAGS: -lMLIRBufferizationTransforms
#cgo LDFLAGS: -lMLIRBuiltinToLLVMIRTranslation
#cgo LDFLAGS: -lMLIRBytecodeOpInterface
#cgo LDFLAGS: -lMLIRBytecodeReader
#cgo LDFLAGS: -lMLIRBytecodeWriter
#cgo LDFLAGS: -lMLIRCallInterfaces
#cgo LDFLAGS: -lMLIRCAPIAMDGPU
#cgo LDFLAGS: -lMLIRCAPIArith
#cgo LDFLAGS: -lMLIRCAPIAsync
#cgo LDFLAGS: -lMLIRCAPIControlFlow
#cgo LDFLAGS: -lMLIRCAPIConversion
#cgo LDFLAGS: -lMLIRCAPIDebug
#cgo LDFLAGS: -lMLIRCAPIEmitC
#cgo LDFLAGS: -lMLIRCAPIExportSMTLIB
#cgo LDFLAGS: -lMLIRCAPIFunc
#cgo LDFLAGS: -lMLIRCAPIGPU
#cgo LDFLAGS: -lMLIRCAPIIndex
#cgo LDFLAGS: -lMLIRCAPIInterfaces
#cgo LDFLAGS: -lMLIRCAPIIR
#cgo LDFLAGS: -lMLIRCAPIIRDL
#cgo LDFLAGS: -lMLIRCAPILinalg
#cgo LDFLAGS: -lMLIRCAPILLVM
#cgo LDFLAGS: -lMLIRCAPIMath
#cgo LDFLAGS: -lMLIRCAPIMemRef
#cgo LDFLAGS: -lMLIRCAPIMLProgram
#cgo LDFLAGS: -lMLIRCAPINVGPU
#cgo LDFLAGS: -lMLIRCAPINVVM
#cgo LDFLAGS: -lMLIRCAPIOpenMP
#cgo LDFLAGS: -lMLIRCAPIPDL
#cgo LDFLAGS: -lMLIRCAPIQuant
#cgo LDFLAGS: -lMLIRCAPIRegisterEverything
#cgo LDFLAGS: -lMLIRCAPIROCDL
#cgo LDFLAGS: -lMLIRCAPISCF
#cgo LDFLAGS: -lMLIRCAPIShape
#cgo LDFLAGS: -lMLIRCAPISMT
#cgo LDFLAGS: -lMLIRCAPISparseTensor
#cgo LDFLAGS: -lMLIRCAPISPIRV
#cgo LDFLAGS: -lMLIRCAPITarget
#cgo LDFLAGS: -lMLIRCAPITensor
#cgo LDFLAGS: -lMLIRCAPITransformDialect
#cgo LDFLAGS: -lMLIRCAPITransformDialectTransforms
#cgo LDFLAGS: -lMLIRCAPITransforms
#cgo LDFLAGS: -lMLIRCAPIVector
#cgo LDFLAGS: -lMLIRCastInterfaces
#cgo LDFLAGS: -lMLIRComplexDialect
#cgo LDFLAGS: -lMLIRComplexDivisionConversion
#cgo LDFLAGS: -lMLIRComplexToLibm
#cgo LDFLAGS: -lMLIRComplexToLLVM
#cgo LDFLAGS: -lMLIRComplexToSPIRV
#cgo LDFLAGS: -lMLIRComplexToStandard
#cgo LDFLAGS: -lMLIRControlFlowDialect
#cgo LDFLAGS: -lMLIRControlFlowInterfaces
#cgo LDFLAGS: -lMLIRControlFlowToLLVM
#cgo LDFLAGS: -lMLIRControlFlowToSCF
#cgo LDFLAGS: -lMLIRControlFlowToSPIRV
#cgo LDFLAGS: -lMLIRControlFlowTransforms
#cgo LDFLAGS: -lMLIRConvertToEmitC
#cgo LDFLAGS: -lMLIRConvertToLLVMInterface
#cgo LDFLAGS: -lMLIRConvertToLLVMPass
#cgo LDFLAGS: -lMLIRCopyOpInterface
#cgo LDFLAGS: -lMLIRDataLayoutInterfaces
#cgo LDFLAGS: -lMLIRDebug
#cgo LDFLAGS: -lMLIRDerivedAttributeOpInterface
#cgo LDFLAGS: -lMLIRDestinationStyleOpInterface
#cgo LDFLAGS: -lMLIRDialect
#cgo LDFLAGS: -lMLIRDialectUtils
#cgo LDFLAGS: -lMLIRDLTIDialect
#cgo LDFLAGS: -lMLIRDLTITransformOps
#cgo LDFLAGS: -lMLIREmitCDialect
#cgo LDFLAGS: -lMLIREmitCTransforms
#cgo LDFLAGS: -lMLIRExecutionEngineUtils
#cgo LDFLAGS: -lMLIRExportSMTLIB
#cgo LDFLAGS: -lMLIRFromLLVMIRTranslationRegistration
#cgo LDFLAGS: -lMLIRFuncAllExtensions
#cgo LDFLAGS: -lMLIRFuncDialect
#cgo LDFLAGS: -lMLIRFuncInlinerExtension
#cgo LDFLAGS: -lMLIRFuncMeshShardingExtensions
#cgo LDFLAGS: -lMLIRFunctionInterfaces
#cgo LDFLAGS: -lMLIRFuncToEmitC
#cgo LDFLAGS: -lMLIRFuncToLLVM
#cgo LDFLAGS: -lMLIRFuncToSPIRV
#cgo LDFLAGS: -lMLIRFuncTransformOps
#cgo LDFLAGS: -lMLIRFuncTransforms
#cgo LDFLAGS: -lMLIRFuncUtils
#cgo LDFLAGS: -lMLIRGPUDialect
#cgo LDFLAGS: -lMLIRGPUPipelines
#cgo LDFLAGS: -lMLIRGPUToGPURuntimeTransforms
#cgo LDFLAGS: -lMLIRGPUToLLVMIRTranslation
#cgo LDFLAGS: -lMLIRGPUToLLVMSPV
#cgo LDFLAGS: -lMLIRGPUToNVVMTransforms
#cgo LDFLAGS: -lMLIRGPUToROCDLTransforms
#cgo LDFLAGS: -lMLIRGPUToSPIRV
#cgo LDFLAGS: -lMLIRGPUTransformOps
#cgo LDFLAGS: -lMLIRGPUTransforms
#cgo LDFLAGS: -lMLIRGPUUtils
#cgo LDFLAGS: -lMLIRIndexDialect
#cgo LDFLAGS: -lMLIRIndexingMapOpInterface
#cgo LDFLAGS: -lMLIRIndexToLLVM
#cgo LDFLAGS: -lMLIRIndexToSPIRV
#cgo LDFLAGS: -lMLIRInferIntRangeCommon
#cgo LDFLAGS: -lMLIRInferIntRangeInterface
#cgo LDFLAGS: -lMLIRInferTypeOpInterface
#cgo LDFLAGS: -lMLIRIR
#cgo LDFLAGS: -lMLIRIRDL
#cgo LDFLAGS: -lMLIRLinalgDialect
#cgo LDFLAGS: -lMLIRLinalgToStandard
#cgo LDFLAGS: -lMLIRLinalgTransformOps
#cgo LDFLAGS: -lMLIRLinalgTransforms
#cgo LDFLAGS: -lMLIRLinalgUtils
#cgo LDFLAGS: -lMLIRLLVMCommonConversion
#cgo LDFLAGS: -lMLIRLLVMDialect
#cgo LDFLAGS: -lMLIRLLVMIRToLLVMTranslation
#cgo LDFLAGS: -lMLIRLLVMIRToNVVMTranslation
#cgo LDFLAGS: -lMLIRLLVMIRTransforms
#cgo LDFLAGS: -lMLIRLLVMToLLVMIRTranslation
#cgo LDFLAGS: -lMLIRLoopLikeInterface
#cgo LDFLAGS: -lMLIRLspServerLib
#cgo LDFLAGS: -lMLIRLspServerSupportLib
#cgo LDFLAGS: -lMLIRMaskableOpInterface
#cgo LDFLAGS: -lMLIRMaskingOpInterface
#cgo LDFLAGS: -lMLIRMathDialect
#cgo LDFLAGS: -lMLIRMathToEmitC
#cgo LDFLAGS: -lMLIRMathToFuncs
#cgo LDFLAGS: -lMLIRMathToLibm
#cgo LDFLAGS: -lMLIRMathToLLVM
#cgo LDFLAGS: -lMLIRMathToROCDL
#cgo LDFLAGS: -lMLIRMathToSPIRV
#cgo LDFLAGS: -lMLIRMathTransforms
#cgo LDFLAGS: -lMLIRMemorySlotInterfaces
#cgo LDFLAGS: -lMLIRMemRefDialect
#cgo LDFLAGS: -lMLIRMemRefToEmitC
#cgo LDFLAGS: -lMLIRMemRefToLLVM
#cgo LDFLAGS: -lMLIRMemRefToSPIRV
#cgo LDFLAGS: -lMLIRMemRefTransformOps
#cgo LDFLAGS: -lMLIRMemRefTransforms
#cgo LDFLAGS: -lMLIRMemRefUtils
#cgo LDFLAGS: -lMLIRMeshDialect
#cgo LDFLAGS: -lMLIRMeshToMPI
#cgo LDFLAGS: -lMLIRMeshTransforms
#cgo LDFLAGS: -lMLIRMlirOptMain
#cgo LDFLAGS: -lMLIRMLProgramDialect
#cgo LDFLAGS: -lMLIRMLProgramTransforms
#cgo LDFLAGS: -lMLIRMPIDialect
#cgo LDFLAGS: -lMLIRMPIToLLVM
#cgo LDFLAGS: -lMLIRNVGPUDialect
#cgo LDFLAGS: -lMLIRNVGPUToNVVM
#cgo LDFLAGS: -lMLIRNVGPUTransformOps
#cgo LDFLAGS: -lMLIRNVGPUTransforms
#cgo LDFLAGS: -lMLIRNVGPUUtils
#cgo LDFLAGS: -lMLIRNVVMDialect
#cgo LDFLAGS: -lMLIRNVVMTarget
#cgo LDFLAGS: -lMLIRNVVMToLLVM
#cgo LDFLAGS: -lMLIRNVVMToLLVMIRTranslation
#cgo LDFLAGS: -lMLIRObservers
#cgo LDFLAGS: -lMLIROpenACCDialect
#cgo LDFLAGS: -lMLIROpenACCMPCommon
#cgo LDFLAGS: -lMLIROpenACCToLLVMIRTranslation
#cgo LDFLAGS: -lMLIROpenACCToSCF
#cgo LDFLAGS: -lMLIROpenACCTransforms
#cgo LDFLAGS: -lMLIROpenMPDialect
#cgo LDFLAGS: -lMLIROpenMPToLLVM
#cgo LDFLAGS: -lMLIROpenMPToLLVMIRTranslation
#cgo LDFLAGS: -lMLIROptLib
#cgo LDFLAGS: -lMLIRParallelCombiningOpInterface
#cgo LDFLAGS: -lMLIRParser
#cgo LDFLAGS: -lMLIRPass
#cgo LDFLAGS: -lMLIRPDLDialect
#cgo LDFLAGS: -lMLIRPDLInterpDialect
#cgo LDFLAGS: -lMLIRPDLLAST
#cgo LDFLAGS: -lMLIRPDLLCodeGen
#cgo LDFLAGS: -lMLIRPdllLspServerLib
#cgo LDFLAGS: -lMLIRPDLLODS
#cgo LDFLAGS: -lMLIRPDLLParser
#cgo LDFLAGS: -lMLIRPDLToPDLInterp
#cgo LDFLAGS: -lMLIRPluginsLib
#cgo LDFLAGS: -lMLIRPresburger
#cgo LDFLAGS: -lMLIRPtrDialect
#cgo LDFLAGS: -lMLIRQuantDialect
#cgo LDFLAGS: -lMLIRQuantTransforms
#cgo LDFLAGS: -lMLIRQuantUtils
#cgo LDFLAGS: -lMLIRQuery
#cgo LDFLAGS: -lMLIRQueryLib
#cgo LDFLAGS: -lMLIRQueryMatcher
#cgo LDFLAGS: -lMLIRReconcileUnrealizedCasts
#cgo LDFLAGS: -lMLIRReduce
#cgo LDFLAGS: -lMLIRReduceLib
#cgo LDFLAGS: -lMLIRRewrite
#cgo LDFLAGS: -lMLIRRewritePDL
#cgo LDFLAGS: -lMLIRROCDLDialect
#cgo LDFLAGS: -lMLIRROCDLTarget
#cgo LDFLAGS: -lMLIRROCDLToLLVMIRTranslation
#cgo LDFLAGS: -lMLIRRuntimeVerifiableOpInterface
#cgo LDFLAGS: -lMLIRSCFDialect
#cgo LDFLAGS: -lMLIRSCFToControlFlow
#cgo LDFLAGS: -lMLIRSCFToEmitC
#cgo LDFLAGS: -lMLIRSCFToGPU
#cgo LDFLAGS: -lMLIRSCFToOpenMP
#cgo LDFLAGS: -lMLIRSCFToSPIRV
#cgo LDFLAGS: -lMLIRSCFTransformOps
#cgo LDFLAGS: -lMLIRSCFTransforms
#cgo LDFLAGS: -lMLIRSCFUtils
#cgo LDFLAGS: -lMLIRShapeDialect
#cgo LDFLAGS: -lMLIRShapedOpInterfaces
#cgo LDFLAGS: -lMLIRShapeOpsTransforms
#cgo LDFLAGS: -lMLIRShapeToStandard
#cgo LDFLAGS: -lMLIRShardingInterface
#cgo LDFLAGS: -lMLIRSideEffectInterfaces
#cgo LDFLAGS: -lMLIRSMT
#cgo LDFLAGS: -lMLIRSparseTensorDialect
#cgo LDFLAGS: -lMLIRSparseTensorPipelines
#cgo LDFLAGS: -lMLIRSparseTensorTransformOps
#cgo LDFLAGS: -lMLIRSparseTensorTransforms
#cgo LDFLAGS: -lMLIRSparseTensorUtils
#cgo LDFLAGS: -lMLIRSPIRVAttrToLLVMConversion
#cgo LDFLAGS: -lMLIRSPIRVBinaryUtils
#cgo LDFLAGS: -lMLIRSPIRVConversion
#cgo LDFLAGS: -lMLIRSPIRVDeserialization
#cgo LDFLAGS: -lMLIRSPIRVDialect
#cgo LDFLAGS: -lMLIRSPIRVImageInterfaces
#cgo LDFLAGS: -lMLIRSPIRVModuleCombiner
#cgo LDFLAGS: -lMLIRSPIRVSerialization
#cgo LDFLAGS: -lMLIRSPIRVTarget
#cgo LDFLAGS: -lMLIRSPIRVToLLVM
#cgo LDFLAGS: -lMLIRSPIRVToLLVMIRTranslation
#cgo LDFLAGS: -lMLIRSPIRVTransforms
#cgo LDFLAGS: -lMLIRSPIRVTranslateRegistration
#cgo LDFLAGS: -lMLIRSPIRVUtils
#cgo LDFLAGS: -lMLIRSubsetOpInterface
#cgo LDFLAGS: -lMLIRSupport
#cgo LDFLAGS: -lMLIRTableGen
#cgo LDFLAGS: -lMLIRTargetCpp
#cgo LDFLAGS: -lMLIRTargetIRDLToCpp
#cgo LDFLAGS: -lMLIRTargetLLVM
#cgo LDFLAGS: -lMLIRTargetLLVMIRExport
#cgo LDFLAGS: -lMLIRTargetLLVMIRImport
#cgo LDFLAGS: -lMLIRTblgenLib
#cgo LDFLAGS: -lMLIRTensorAllExtensions
#cgo LDFLAGS: -lMLIRTensorDialect
#cgo LDFLAGS: -lMLIRTensorInferTypeOpInterfaceImpl
#cgo LDFLAGS: -lMLIRTensorMeshShardingExtensions
#cgo LDFLAGS: -lMLIRTensorTilingInterfaceImpl
#cgo LDFLAGS: -lMLIRTensorToLinalg
#cgo LDFLAGS: -lMLIRTensorToSPIRV
#cgo LDFLAGS: -lMLIRTensorTransformOps
#cgo LDFLAGS: -lMLIRTensorTransforms
#cgo LDFLAGS: -lMLIRTensorUtils
#cgo LDFLAGS: -lMLIRTilingInterface
#cgo LDFLAGS: -lMLIRToLLVMIRTranslationRegistration
#cgo LDFLAGS: -lMLIRTosaDialect
#cgo LDFLAGS: -lMLIRTosaShardingInterfaceImpl
#cgo LDFLAGS: -lMLIRTosaToArith
#cgo LDFLAGS: -lMLIRTosaToLinalg
#cgo LDFLAGS: -lMLIRTosaToMLProgram
#cgo LDFLAGS: -lMLIRTosaToSCF
#cgo LDFLAGS: -lMLIRTosaToTensor
#cgo LDFLAGS: -lMLIRTosaTransforms
#cgo LDFLAGS: -lMLIRTransformDebugExtension
#cgo LDFLAGS: -lMLIRTransformDialect
#cgo LDFLAGS: -lMLIRTransformDialectInterfaces
#cgo LDFLAGS: -lMLIRTransformDialectIRDLExtension
#cgo LDFLAGS: -lMLIRTransformDialectTransforms
#cgo LDFLAGS: -lMLIRTransformDialectUtils
#cgo LDFLAGS: -lMLIRTransformLoopExtension
#cgo LDFLAGS: -lMLIRTransformPDLExtension
#cgo LDFLAGS: -lMLIRTransforms
#cgo LDFLAGS: -lMLIRTransformTuneExtension
#cgo LDFLAGS: -lMLIRTransformUtils
#cgo LDFLAGS: -lMLIRTranslateLib
#cgo LDFLAGS: -lMLIRUBDialect
#cgo LDFLAGS: -lMLIRUBToLLVM
#cgo LDFLAGS: -lMLIRUBToSPIRV
#cgo LDFLAGS: -lMLIRValueBoundsOpInterface
#cgo LDFLAGS: -lMLIRVCIXDialect
#cgo LDFLAGS: -lMLIRVCIXToLLVMIRTranslation
#cgo LDFLAGS: -lMLIRVectorDialect
#cgo LDFLAGS: -lMLIRVectorInterfaces
#cgo LDFLAGS: -lMLIRVectorToArmSME
#cgo LDFLAGS: -lMLIRVectorToGPU
#cgo LDFLAGS: -lMLIRVectorToLLVM
#cgo LDFLAGS: -lMLIRVectorToLLVMPass
#cgo LDFLAGS: -lMLIRVectorToSCF
#cgo LDFLAGS: -lMLIRVectorToSPIRV
#cgo LDFLAGS: -lMLIRVectorToXeGPU
#cgo LDFLAGS: -lMLIRVectorTransformOps
#cgo LDFLAGS: -lMLIRVectorTransforms
#cgo LDFLAGS: -lMLIRVectorUtils
#cgo LDFLAGS: -lMLIRViewLikeInterface
#cgo LDFLAGS: -lMLIRX86VectorDialect
#cgo LDFLAGS: -lMLIRX86VectorTransforms
#cgo LDFLAGS: -lMLIRXeGPUDialect
#cgo LDFLAGS: -lMLIRXeGPUTransforms
#cgo LDFLAGS: -lMLIRXeGPUUtils
#cgo LDFLAGS: -lMLIRXeVMDialect
#cgo LDFLAGS: -lMLIRXeVMToLLVM
*/
import "C"
